name: EatStuff
version: '1.1-FRUITS'
main: dev.furrygang.eatStuff.EatStuff
api-version: '1.21'
authors: [ furrygang, Openmindedness ]
description: hi :3
commands:
  leaderboard:
    aliases: lb
    description: "Show how much have people ate so far"
    usage: "leaderboard"